### ISSUE TITLE
Cannot find module fs/promises

### ISSUE THREAD

**Issue by frekkanzer2** [frekkanzer2/HorizonGram#11]
Here's the error received when installed from zero on an OPI Zero3:

maintainer@orangepizero3:/horizongram/HorizonGram-3-pre-r1/server$ sudo npm start

> server@1.0.0 start
> node server.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /horizongram/HorizonGram-3-pre-r1/server/utils/settings-config.js
- /horizongram/HorizonGram-3-pre-r1/server/controllers/c-folders.js
- /horizongram/HorizonGram-3-pre-r1/server/utils/engine.js
- /horizongram/HorizonGram-3-pre-r1/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/horizongram/HorizonGram-3-pre-r1/server/utils/settings-config.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/horizongram/HorizonGram-3-pre-r1/server/utils/settings-config.js',
    '/horizongram/HorizonGram-3-pre-r1/server/controllers/c-folders.js',
    '/horizongram/HorizonGram-3-pre-r1/server/utils/engine.js',
    '/horizongram/HorizonGram-3-pre-r1/server/server.js'
  ]
}
npm ERR! code 1
npm ERR! path /horizongram/HorizonGram-3-pre-r1/server
npm ERR! command failed
npm ERR! command sh -c node server.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-12-13T02_15_52_313Z-debug.log

**Comment by frekkanzer2** [comment]
Solved by upgrading to node 14.
It will be reported in documentation.
