### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by frekkanzer2** [frekkanzer2/HorizonGram#5]
Executed commands:
[][][][][][][][][][][][][][][][][][][][][][][][][]
npm start
[][][][][][][][][][][][][][][][][][][][][][][][][]

Logs:
[][][][][][][][][][][][][][][][][][][][][][][][][]
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1310:16)
    at listenInCluster (net.js:1358:12)
    at Server.listen (net.js:1444:7)
    at Function.listen (/mnt/c/Users/fr.abate/Downloads/HorizonGram-1.2/HorizonGram-1.2/server/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/mnt/c/Users/fr.abate/Downloads/HorizonGram-1.2/HorizonGram-1.2/server/server.js:44:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1337:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}
[][][][][][][][][][][][][][][][][][][][][][][][][]

This happens when the port is already used.
Add a preliminary check when server starts and show a custom message.

**Comment by frekkanzer2** [comment]
Solved in v1.3
